### ISSUE TITLE
Test failures on CPANTESTERS (v0.008)

### ISSUE THREAD

**Issue by ehuelsmann** [skbkontur/perl-jsonschema-validator#13]
Version 0.008 fails on some testers with Perls older than 5.22, see http://matrix.cpantesters.org/?dist=JSONSchema-Validator+0.008

I wasn't able to figure out the common denominator, but it seems like a missing dependency or an incorrect minimum dependency.

**Comment by Logioniz** [comment]
Sorry that I did not reply for a while.

I am aware of this problem, but I do not know how to determine what the problem is ...
Do you have any ideas?

It would be nice if I could somehow take and debug under this environment, but I do not know how to do it.

**Comment by ehuelsmann** [comment]
@Logioniz Maybe we can contact the administrator of the failing machine. But before doing that, can we somehow add code or tests which make clear what expectation is failing? I only see that a specific use-case fails, but I can't see where in the callstack the problem occurs. I'd love to PR more detailed tests, but I'll need some help to understand what the failing test is trying to determine.

**Comment by Logioniz** [comment]
Ok, let's consider this failed test:
```
#   Failed test 'draft4: additionalProperties: an additional valid property is valid'
#   at t/json_schema.t line 30.
#          got: '0'
#     expected: '1'
```

This error matches [this](https://github.com/skbkontur/perl-jsonschema-validator/blob/master/t/data/json_schema/draft4/basic.json#L45-L68) test.

In fact, it corresponds to the given code:
```perl
#!/usr/bin/perl
use strict;
use warnings;
use JSON::PP 'decode_json';
use JSONSchema::Validator;
use Test::More;
my $v = JSONSchema::Validator->new(
                schema => decode_json('{
                        "properties": {"foo": {}, "bar": {}},
                        "additionalProperties": {"type": "boolean"}
                }'),
                validate_schema => 0,
                specification => 'draft4'
            );
my ($result, $errors) = $v->validate_schema(decode_json('{"foo" : 1, "bar" : 2, "quux" : true}'));
is $result, 1, 'an additional valid property is valid';
done_testing;
```

This test checks the _additionalProperties_ constraint. Essentially checks that the _quux_ property is a type boolean.

**Comment by Logioniz** [comment]
I built exactly the same environment (FreeBSD 10.1 amd64) with exactly the same versions of modules as in [this test](http://www.cpantesters.org/cpan/report/cd559aa0-1b02-11ec-bcea-6e1c1f24ea8f), compiled perl so that it was of exactly the same version (5.20.1) and with the same options (-Duse64bitall -Duselongdouble) and tests everything both succeed.

I have no idea what to test anymore. It remains only to contact the administrator (Slaven Rezić) of that machine.

**Comment by ehuelsmann** [comment]
I've asked in the libera.chat #perl channel about this. They have two options:

1. Add `diag()` and `note()` calls in the tests (and/or litter the code with `print STDERR` statements) and do a `TRIAL` upload
2. Contact SREZIC on his equally named cpan.org mail address and ask for help

He's said to be very approachable.

I'd like to help, but don't know which `print` statements to litter into the code. (I don't have any failures locally either...). If you are going to meet in a chat channel, I'd like to join, I'd love to be on Cc in the mail conversation, but I don't think there's anything immediate that I'd be able to do. Please let me know if you think otherwise.

**Comment by Logioniz** [comment]
The first option came up.
http://www.cpantesters.org/cpan/report/04846b54-515f-11ec-9647-4d571f24ea8f

It looks like an additional module is installed on the system, which is not displayed in the list: `JSON::XS`. 

So, boolean value has type JSON::XS::Boolean, but we check JSON::PP::Boolean in strict mode.

In general, I don't like checking types, but there is no boolean types/class in the perl, and [these tests](https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/master/tests/draft4/type.json#L233-L287) need to be passed somehow, so I had to do just that (to check class JSON::PP::Boolean).

**Comment by ehuelsmann** [comment]
To compensate for the different JSON modules that can be used, you could consider using JSON::MaybeXS, which imports the booleans from the module it ends up using and reexports those under a name that's known in advance.

**Comment by ehuelsmann** [comment]
But it's great that the trial run showed enough information to address this issue!
