### ISSUE TITLE
Use of uninitialized value $scheme

### ISSUE THREAD

**Issue by 0-wiz-0** [skbkontur/perl-jsonschema-validator#16]
When the validator constructor is passed a file name, not a URL, perl reports errors for the module:
```
my $validator = JSONSchema::Validator->new(resource => 'some.yaml');
```
gives
```
Use of uninitialized value $scheme in exists at /usr/pkg/lib/perl5/vendor_perl/5.34.0/JSONSchema/Validator/Util.pm line 125.
Use of uninitialized value $scheme in string eq at /usr/pkg/lib/perl5/vendor_perl/5.34.0/JSONSchema/Validator/Util.pm line 127.
Unsupported scheme of uri some.yaml at /usr/pkg/lib/perl5/vendor_perl/5.34.0/JSONSchema/Validator.pm line 112.
```

**Comment by Logioniz** [comment]
Needs to be used something like this:
```perl
my $validator = JSONSchema::Validator->new(resource => 'file:///some/path/to/some.yaml');
``` 
The scheme **file://** is required. I add ability not to set scheme explicitly in #17.

Also some.yml must contains `$schema` keyword. If `$schema` is not there, then you need to specify the `specification` parameter.

**Comment by 0-wiz-0** [comment]
Sorry, I wasn't clear in my bug report.
It's fine that a file without `file://` prefix is not supported, and I fixed that locally.

But it should report an error, not let perl drop warnings about variables. 

I hope it's clearer now.

**Comment by Logioniz** [comment]
Yes, i think to report with error in such case but lately decide to support file path which more intuitive for users.
