### ISSUE TITLE
Required header not validated when `header` not passed

### ISSUE THREAD

**Issue by ehuelsmann** [skbkontur/perl-jsonschema-validator#29]
A schema which requires a specific header in a request (e.g. ETag), will successfully validate, even if it can't validate the headers, because the `header` parameter is missing.

There are two possible solutions:

1. Throw an error right at the start, when the user parameters are being wrapped, explaining the schema requires validation of parameters of type `header` (or any of the others) and that the type isn't passed in
2. Generate empty values for all headers/url parameters/... the library tries to validate.

Both are a small change. Let me know which you prefer.

I personally prefer (1), because it's most clear to the programmer what's the problem that needs solving.

**Comment by avkhozov** [comment]
+1 for the first option
